import { Member } from "@src/types";

export const members: Member[] = [
  {
    id: "kokopp",
    name: "川越マガジン",
    role: "",
    bio: "川越ニュース運営",
    avatarSrc: "/avatars/kokopp.jpg",
    sources: [
      "https://kawagoe.fun/magazine/feed/",
      // "https://kawagoe.traveler20.site/feed.xml",
      // "https://note.com/kokopp/rss",
    ],
    // includeUrlRegex: "gallery|article",
    // excludeUrlRegex: "blog",
    twitterUsername: "kawagoemagazine",
    instagramUsername: "kokopp_kawagoe",
    githubUsername: "",
    websiteUrl: "https://kawagoe.fun/magazine/",
  },
  {
    id: "goguynet",
    name: "号外ネット",
    role: "",
    bio: "号外ネットの川越版。",
    avatarSrc: "/avatars/goguynet.jpg",
    sources: ["https://kawagoe.goguynet.jp/feed/"],
    twitterUsername: "",
    instagramUsername: "",
    githubUsername: "",
    websiteUrl: "https://kawagoe.goguynet.jp/",
  },
  {
    id: "kawagoe_keizai_biz",
    name: "川越経済新聞",
    role: "",
    bio: "広域川越圏のビジネス＆カルチャーニュース",
    avatarSrc: "/avatars/kawagoe_keizai_biz.jpg",
    sources: ["https://kawagoe.keizai.biz/rss.xml"],
    twitterUsername: "",
    instagramUsername: "",
    githubUsername: "",
    websiteUrl: "https://kawagoe.keizai.biz/",
  },
  {
    id: "kawagoe_info",
    name: "川越水先案内板",
    role: "",
    bio: "",
    avatarSrc: "/avatars/kawagoe_info.jpg",
    sources: ["https://kawagoe-info.net/feed/"],
    twitterUsername: "kawagoemizusaki",
    instagramUsername: "",
    githubUsername: "",
    websiteUrl: "https://kawagoe-info.net/",
  },
  {
    id: "korokoro",
    name: "小江戸川越STYLE",
    role: "",
    bio: "",
    avatarSrc: "/avatars/korokoro.jpg",
    sources: ["https://ameblo.jp/korokoro0105/rss.html"],
    twitterUsername: "SHIN8KOKO",
    instagramUsername: "",
    githubUsername: "",
    websiteUrl: "https://ameblo.jp/korokoro0105",
  },
  {
    id: "hash_kawagoe",
    name: "#川越(ハッシュカワゴエ)",
    role: "",
    bio: "",
    avatarSrc: "/avatars/hash_kawagoe.jpg",
    sources: ["https://mag.c-kawagoe.com/feed"],
    twitterUsername: "coedo_kawagoe",
    instagramUsername: "coedokawagoe",
    githubUsername: "",
    websiteUrl: "https://mag.c-kawagoe.com/",
  },
  {
    id: "kawagoe_tv",
    name: "川越TV",
    role: "",
    bio: "",
    avatarSrc: "/avatars/kawagoe_tv.jpg",
    sources: ["https://kawagoe.tv/feed/"],
    twitterUsername: "kawagoe_tv",
    instagramUsername: "kawagoe.tv",
    githubUsername: "",
    websiteUrl: "https://kawagoe.tv/",
  },
  {
    id: "kawagoe_blog",
    name: "川越ノヲト。",
    role: "",
    bio: "",
    avatarSrc: "/avatars/kawagoe_blog.jpg",
    sources: ["https://kawagoe-blog.com/feed/"],
    twitterUsername: "coedokko201Q",
    instagramUsername: "",
    githubUsername: "",
    websiteUrl: "https://kawagoe-blog.com",
  },
  {
    id: "saitama_city_marathon",
    name: "埼玉マガジン 川越市",
    role: "",
    bio: "",
    avatarSrc: "/avatars/saitama_city_marathon.jpg",
    sources: ["https://saitama-city-marathon.jp/tag/kawagoesi/feed/"],
    twitterUsername: "saitamamagagin",
    instagramUsername: "saitama._.magajin",
    githubUsername: "",
    websiteUrl: "https://saitama-city-marathon.jp/tag/kawagoesi/",
  },
  {
    id: "jikomanpuku",
    name: "食べて埼玉 川越市",
    role: "",
    bio: "",
    avatarSrc: "/avatars/jikomanpuku.jpg",
    sources: [
      "https://jikomanpuku.com/category/%E5%9F%BC%E7%8E%89%E5%B8%82%E7%94%BA%E6%9D%91%E5%88%A5/%E5%B7%9D%E8%B6%8A%E5%B8%82/feed/",
    ],
    twitterUsername: "komashi",
    instagramUsername: "komashi_morituke",
    githubUsername: "",
    websiteUrl:
      "https://jikomanpuku.com/category/%e5%9f%bc%e7%8e%89%e5%b8%82%e7%94%ba%e6%9d%91%e5%88%a5/%e5%b7%9d%e8%b6%8a%e5%b8%82/",
  },
  {
    id: "kawagoemarket",
    name: "川越Farmer’s Market",
    role: "",
    bio: "",
    avatarSrc: "/avatars/kawagoemarket.jpg",
    sources: ["https://ameblo.jp/kawagoemarket/rss.html"],
    twitterUsername: "",
    instagramUsername: "",
    githubUsername: "",
    websiteUrl: "https://ameblo.jp/kawagoemarket",
  },
  {
    id: "hanavi",
    name: "HANAVi KAWAGOE",
    role: "",
    bio: "",
    avatarSrc: "/avatars/hanavi.jpg",
    sources: ["https://hanavi.art/portal/feed/"],
    twitterUsername: "",
    instagramUsername: "https://www.instagram.com/hanavi_portal/",
    githubUsername: "",
    websiteUrl: "https://hanavi.art/portal/",
  },
  {
    id: "kawagoe_ichibangai",
    name: "川越一番街商店街",
    role: "",
    bio: "",
    avatarSrc: "/avatars/kawagoe_ichibangai.jpg",
    sources: ["https://kawagoe-ichibangai.com/feed/"],
    twitterUsername: "",
    instagramUsername: "",
    githubUsername: "",
    websiteUrl: "https://kawagoe-ichibangai.com/",
  },
  {
    id: "koedo_biz",
    name: "川越なび",
    role: "",
    bio: "",
    avatarSrc: "/avatars/koedo_biz.jpg",
    sources: ["https://www.koedo.biz/feed/"],
    twitterUsername: "",
    instagramUsername: "kawagoe_navi",
    githubUsername: "",
    websiteUrl: "https://www.koedo.biz/",
  },
  // {
  //   id: "kawagoe_life",
  //   name: "川越のいいところ",
  //   role: "",
  //   bio: "",
  //   avatarSrc: "/avatars/kawagoe_life.jpg",
  //   sources: ["https://kawagoe-life.com/feed/"],
  //   twitterUsername: "e_naka11",
  //   instagramUsername: "",
  //   githubUsername: "",
  //   websiteUrl: "https://kawagoe-life.com/",
  // },
  {
    id: "koedo_info",
    name: "カワゴエ・マス・メディア",
    role: "",
    bio: "",
    avatarSrc: "/avatars/koedo_info.jpg",
    sources: ["https://koedo.info/feed/"],
    twitterUsername: "KawagoePortal",
    instagramUsername: "kawagoeportal",
    githubUsername: "",
    websiteUrl: "https://koedo.info/",
  },
  {
    id: "kawagoe_com",
    name: "川越インターネットモール",
    role: "",
    bio: "小江戸川越に関する情報メディア",
    avatarSrc: "/avatars/kawagoe_com.jpg",
    sources: ["https://www.kawagoe.com/atom.xml"],
    twitterUsername: "",
    instagramUsername: "",
    githubUsername: "",
    websiteUrl: "https://www.kawagoe.com/",
  },
];
