import { Member } from "@src/types";

export const members: Member[] = [
  {
    id: "kokopp",
    name: "ここっぷ",
    role: "",
    bio: "運営者",
    avatarSrc: "/avatars/kokopp.jpg",
    // sources: [
    // "https://kawagoe.traveler20.site/feed.xml",
    // "https://note.com/kokopp/rss",
    // ],
    includeUrlRegex: "gallery|article",
    excludeUrlRegex: "blog",
    twitterUsername: "",
    instagramUsername: "kokopp_kawagoe",
    githubUsername: "",
    websiteUrl: "https://www.threads.net/@kokopp_kawagoe",
  },
  {
    id: "goguynet",
    name: "号外ネット",
    role: "",
    bio: "号外ネットの川越版。",
    avatarSrc: "/avatars/goguynet.jpg",
    sources: ["https://kawagoe.goguynet.jp/feed/"],
    twitterUsername: "",
    instagramUsername: "",
    githubUsername: "",
    websiteUrl: "https://kawagoe.goguynet.jp/",
  },
  {
    id: "kawagoe_blog",
    name: "川越ノオト",
    role: "",
    bio: "",
    avatarSrc: "/avatars/kawagoe_blog.jpg",
    sources: ["https://kawagoe-blog.com/feed/"],
    twitterUsername: "coedokko201Q",
    instagramUsername: "",
    githubUsername: "",
    websiteUrl: "https://kawagoe-blog.com",
  },
  {
    id: "korokoro",
    name: "小江戸川越STYLE",
    role: "",
    bio: "",
    avatarSrc: "/avatars/korokoro.jpg",
    sources: ["https://ameblo.jp/korokoro0105/rss.html"],
    twitterUsername: "SHIN8KOKO",
    instagramUsername: "",
    githubUsername: "",
    websiteUrl: "https://ameblo.jp/korokoro0105",
  },
  {
    id: "kawagoemarket",
    name: "川越Farmer’s Market",
    role: "",
    bio: "",
    avatarSrc: "/avatars/kawagoemarket.jpg",
    sources: ["https://ameblo.jp/kawagoemarket/rss.html"],
    twitterUsername: "",
    instagramUsername: "",
    githubUsername: "",
    websiteUrl: "https://ameblo.jp/kawagoemarket",
  },
  {
    id: "kawagoe_ichibangai",
    name: "川越一番街商店街",
    role: "",
    bio: "",
    avatarSrc: "/avatars/kawagoe_ichibangai.jpg",
    sources: ["https://kawagoe-ichibangai.com/feed/"],
    twitterUsername: "",
    instagramUsername: "",
    githubUsername: "",
    websiteUrl: "https://kawagoe-ichibangai.com/",
  },
  {
    id: "kawagoe_info",
    name: "川越水先案内板",
    role: "",
    bio: "",
    avatarSrc: "/avatars/kawagoe_info.jpg",
    sources: ["https://kawagoe-info.net/feed/"],
    twitterUsername: "kawagoemizusaki",
    instagramUsername: "",
    githubUsername: "",
    websiteUrl: "https://kawagoe-info.net/",
  },
  {
    id: "koedo_biz",
    name: "川越なび",
    role: "",
    bio: "",
    avatarSrc: "/avatars/koedo_biz.jpg",
    sources: ["https://www.koedo.biz/feed/"],
    twitterUsername: "",
    instagramUsername: "kawagoe_navi",
    githubUsername: "",
    websiteUrl: "https://www.koedo.biz/",
  },
  // {
  //   id: "kawagoe_life",
  //   name: "川越のいいところ",
  //   role: "",
  //   bio: "",
  //   avatarSrc: "/avatars/kawagoe_life.jpg",
  //   sources: ["https://kawagoe-life.com/feed/"],
  //   twitterUsername: "e_naka11",
  //   instagramUsername: "",
  //   githubUsername: "",
  //   websiteUrl: "https://kawagoe-life.com/",
  // },
  {
    id: "koedo_info",
    name: "カワゴエ・マス・メディア",
    role: "",
    bio: "",
    avatarSrc: "/avatars/koedo_info.jpg",
    sources: ["https://koedo.info/feed/"],
    twitterUsername: "KawagoePortal",
    instagramUsername: "kawagoeportal",
    githubUsername: "",
    websiteUrl: "https://koedo.info/",
  },
  {
    id: "hash_kawagoe",
    name: "#川越(ハッシュカワゴエ)",
    role: "",
    bio: "",
    avatarSrc: "/avatars/hash_kawagoe.jpg",
    sources: ["https://mag.c-kawagoe.com/feed"],
    twitterUsername: "coedo_kawagoe",
    instagramUsername: "coedokawagoe",
    githubUsername: "",
    websiteUrl: "https://choooodoii.com/",
  },
  {
    id: "kawagoe_com",
    name: "川越インターネットモール",
    role: "",
    bio: "小江戸川越に関する情報メディア",
    avatarSrc: "/avatars/kawagoe_com.jpg",
    sources: ["https://www.kawagoe.com/atom.xml"],
    twitterUsername: "",
    instagramUsername: "",
    githubUsername: "",
    websiteUrl: "https://www.kawagoe.com/",
  },
];
